# Generated by Django 2.1.2 on 2019-01-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20181214_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('environment', models.TextField()),
                ('URL', models.URLField()),
                ('screenshot_URL', models.URLField()),
                ('severity', models.TextField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('TBD', 'TBD')], default='TBD', max_length=10)),
                ('date_reported', models.DateField()),
                ('fixed', models.BooleanField(default=False)),
                ('date_fixed', models.DateField(default=None)),
                ('fixed_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fixer', to='accounts.Profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Bug Report',
            },
        ),
    ]
