# Generated by Django 2.1.2 on 2019-01-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190106_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='date_fixed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixer', to=settings.AUTH_USER_MODEL),
        ),
    ]
