# Generated by Django 2.1.2 on 2019-01-19 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=20)),
                ('current_version', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.TextSection'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='join_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join', to='home.TextSection'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='our_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='home.TextSection'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='trial_sessions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='home.TextSection'),
        ),
    ]
