# Generated by Django 2.1.2 on 2019-01-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomepageText',
            new_name='HomepageVersion',
        ),
    ]
