# Generated by Django 2.1.2 on 2018-11-29 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlidingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_cancelled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GlidingSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField()),
                ('total_launches', models.IntegerField()),
                ('total_aerotows', models.IntegerField()),
                ('total_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='glidingsignup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='glidingsignup',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.GlidingSession'),
        ),
        migrations.AddField(
            model_name='glidingsession',
            name='attendees',
            field=models.ManyToManyField(through='accounts.GlidingSignup', to='accounts.Profile'),
        ),
    ]
