# Generated by Django 2.1.2 on 2019-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181214_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='launches',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minutes_flown',
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
