# Generated by Django 2.1.2 on 2019-01-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190122_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='glidingsession',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
