# Generated by Django 2.1.2 on 2019-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_glidingsession_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid_member',
            field=models.BooleanField(default=False),
        ),
    ]
